// Official Bill of Materials (BOM) Dataset
// Sourced from Autodesk Inventor Assembly "Assembly CNC Router Desktop.iam"
// & PENS Technical Drawing Sheet 24 / EXPLODE1.pdf
// Project by Kelompok DESKTOP CNC ROUTER (Mechatronics PENS)

const BOM_DATA = [
  {
    itemNo: 1,
    name: "Ball Screw SFU1605 (Long - 1000 mm)",
    partNumber: "SFU1605-1000",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 2,
    material: "Bearing Steel GCr15 / Carbon Steel S55C",
    specs: "Diameter 16 mm, Lead/Pitch 5 mm, Panjang 1000 mm, Akurasi Kelas C7",
    function: "Penggerak linear sumbu X dan Y dengan efisiensi mekanik >90% dan backlash sangat rendah.",
    sheetRef: 6
  },
  {
    itemNo: 2,
    name: "Bearing Support BF12 (Floating Side)",
    partNumber: "BF12 id 10mm",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 2,
    material: "Carbon Steel Housing + Deep Groove Ball Bearing",
    specs: "Bore Ø10 mm, Lebar 20 mm, Lubang Baut M6",
    function: "Menumpu ujung bebas poros ballscrew agar dapat bergerak bebas saat mengalami ekspansi termal.",
    sheetRef: 8
  },
  {
    itemNo: 3,
    name: "Bearing Support BK12 (Fixed Side)",
    partNumber: "BK12 id 12mm",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 2,
    material: "Carbon Steel + Angular Contact Ball Bearings",
    specs: "Bore Ø12 mm, Lebar 24 mm, Dilengkapi Locknut M12x1",
    function: "Menahan beban aksial tekan dan tarik yang dihasilkan saat proses pemotongan material oleh spindle.",
    sheetRef: 9
  },
  {
    itemNo: 4,
    name: "Gantry Side Plate 1 (Kanan)",
    partNumber: "Gantry 1",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium Alloy 6061-T6 (Tebal 10 mm)",
    specs: "Dimensi 400.2 × 170.5 × 10 mm, Lubang Presisi CNC M5 & M6",
    function: "Pelat struktural vertikal kanan yang menopang gantry melintang dan meluncur di atas 2 bearing block SBR12UU.",
    sheetRef: 2
  },
  {
    itemNo: 5,
    name: "Gantry Side Plate 2 (Kiri)",
    partNumber: "Gantry 2",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium Alloy 6061-T6 (Tebal 10 mm)",
    specs: "Dimensi 400.2 × 170.5 × 10 mm, Lubang Presisi CNC M5 & M6",
    function: "Pelat struktural vertikal kiri penopang gantry melintang, dudukan motor stepper penggerak sumbu X.",
    sheetRef: 2
  },
  {
    itemNo: 6,
    name: "Linear Guide Bearing Block SBR12UU",
    partNumber: "SBR12UU Bearing Block v1",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 8,
    material: "Aluminium Anodized Housing + GCr15 Steel Balls",
    specs: "Bore Ø12 mm, Panjang 39 mm, Lebar 40 mm, Beban Dinamik 510 N",
    function: "Bantalan peluncur linier sirkulasi bola yang menopang gantry Y dan carriage sumbu X.",
    sheetRef: 12
  },
  {
    itemNo: 7,
    name: "Aluminium Profile 20x40 (Bed Slats)",
    partNumber: "Profil 40x20",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 5,
    material: "Extruded Aluminium 6063-T5",
    specs: "20 × 40 × 978 mm, Dilengkapi lubang tapped M5 interval 441 mm",
    function: "Profil meja kerja tempat peletakan benda kerja (spoilboard) dan clamping fixture.",
    sheetRef: 21
  },
  {
    itemNo: 8,
    name: "Supported Linear Rail SBR12 (Panjang 978 mm)",
    partNumber: "Rail SBR12-978",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 4,
    material: "Hard Chrome-Plated Steel Shaft + Aluminium Support Rail",
    specs: "Shaft Ø12 mm, Kekerasan HRC 58-62, Panjang 978 mm",
    function: "Rel pemandu gerak linier sumbu X dan Y dengan kekakuan tinggi tanpa defleksi.",
    sheetRef: 13
  },
  {
    itemNo: 9,
    name: "Stepper Motor Mount Bracket (NEMA 23)",
    partNumber: "Stepper Bracket",
    category: "actuator",
    categoryLabel: "Aktuator & Motor",
    qty: 2,
    material: "Cast Aluminium Alloy",
    specs: "Flange 57 × 57 mm (NEMA 23 standard), Lubang Tengah Ø26 mm",
    function: "Dudukan rigid untuk motor stepper sumbu X dan Y.",
    sheetRef: 16
  },
  {
    itemNo: 10,
    name: "Hybrid Stepper Motor NEMA 23 (3A 1.9Nm)",
    partNumber: "23HS8430B",
    category: "actuator",
    categoryLabel: "Aktuator & Motor",
    qty: 3,
    material: "Silicon Steel Stator + Neodymium Rotor",
    specs: "Step angle 1.8°, Torsi 1.9 Nm (270 oz-in), Arus 3.0A, 4 Kawat",
    function: "Aktuator penggerak utama pada masing-masing sumbu (X, Y, dan Z).",
    sheetRef: 16
  },
  {
    itemNo: 11,
    name: "Ball Nut Housing DSG16H",
    partNumber: "DSG16H Ball Nut Housing",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 3,
    material: "Cast Aluminium CNC Machined",
    specs: "Bore Ø28 mm, Lubang Baut M5, Lebar 40 mm",
    function: "Dudukan pengikat nut ballscrew SFU1605 ke pelat carriage.",
    sheetRef: 7
  },
  {
    itemNo: 12,
    name: "Ball Screw Flanged Nut SFU1605",
    partNumber: "SFU1605 Nut",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 3,
    material: "Hardened Chrome Steel GCr15",
    specs: "Pitch 5 mm, 4 Sirkulasi Bola Baja Presisi",
    function: "Mengonversi putaran poros motor menjadi gerak translasi linear dengan gesekan minimal.",
    sheetRef: 7
  },
  {
    itemNo: 13,
    name: "Holder Ball Nut Housing Adapter",
    partNumber: "Holder Ball Nut Housing",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 1,
    material: "Aluminium 6061-T6",
    specs: "40 × 40 × 10 mm",
    function: "Adaptor penyambung rumah ball nut ke struktur carriage.",
    sheetRef: 11
  },
  {
    itemNo: 14,
    name: "Aluminium Profile 40x80 Melintang (Gantry Crossbeam)",
    partNumber: "Profil 40x80 melintang",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 2,
    material: "Extruded Aluminium 6063-T5",
    specs: "40 × 80 × 816.36 mm, Heavy Duty Section",
    function: "Balok penopang sumbu X yang menghubungkan kedua pelat gantry samping.",
    sheetRef: 20
  },
  {
    itemNo: 15,
    name: "Aluminium Profile 40x80 Membujur (Base Frame)",
    partNumber: "Profil 40x80 membujur",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 2,
    material: "Extruded Aluminium 6063-T5",
    specs: "40 × 80 × 979.91 mm, Heavy Duty Section",
    function: "Balok utama rangka dasar mesin penopang seluruh jalur sumbu Y.",
    sheetRef: 19
  },
  {
    itemNo: 16,
    name: "End Plate Depan",
    partNumber: "End Plate 1",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium Plate 6061 (Tebal 8 mm)",
    specs: "250 × 956.61 × 8 mm",
    function: "Menutup bagian depan rangka dan mengunci kesejajaran profil dasar.",
    sheetRef: 1
  },
  {
    itemNo: 17,
    name: "End Plate Belakang",
    partNumber: "End Plate 2",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium Plate 6061 (Tebal 8 mm)",
    specs: "250 × 956.61 × 8 mm",
    function: "Menutup bagian belakang rangka dan dudukan bearing support sumbu Y.",
    sheetRef: 1
  },
  {
    itemNo: 18,
    name: "Baut Countersunk M10 x 50",
    partNumber: "ISO 7047 - M10x50",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 2,
    material: "High Tensile Steel Grade 8.8",
    specs: "M10 × 50 mm",
    function: "Pengikat struktural sudut beban tinggi.",
    sheetRef: 24
  },
  {
    itemNo: 19,
    name: "Base Z-Axis Carriage Plate",
    partNumber: "Base spindle / Base Z",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium Plate 6061-T6 (Tebal 8 mm)",
    specs: "248 × 83 × 8 mm, CNC Milled",
    function: "Carriage pembawa rel linier sumbu Z dan dudukan spindle.",
    sheetRef: 3
  },
  {
    itemNo: 20,
    name: "Supported Linear Rail SBR12 (Pendek - 260 mm)",
    partNumber: "Linear Rail Short",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 2,
    material: "Hard Chrome-Plated Steel Shaft + Aluminium Rail",
    specs: "Shaft Ø12 mm, Panjang 260 mm",
    function: "Jalur luncur presisi vertikal sumbu Z.",
    sheetRef: 14
  },
  {
    itemNo: 21,
    name: "Ball Screw SFU1605 (Pendek - 300 mm)",
    partNumber: "Short Leadscrew",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 1,
    material: "Bearing Steel GCr15",
    specs: "Diameter 16 mm, Pitch 5 mm, Panjang 300 mm",
    function: "Poros penggerak vertikal sumbu Z pemegang spindle.",
    sheetRef: 5
  },
  {
    itemNo: 22,
    name: "Linear Guide Bearing Block SBR12UU (Z-Axis)",
    partNumber: "Linear Guide SBR12UU-1",
    category: "motion",
    categoryLabel: "Transmisi & Rel",
    qty: 2,
    material: "Aluminium Housing + GCr15 Steel Balls",
    specs: "Bore Ø12 mm, Open Type",
    function: "Bantalan peluncur langsung pada pelat pembawa spindle.",
    sheetRef: 12
  },
  {
    itemNo: 23,
    name: "Spindle Carrier Mount Plate",
    partNumber: "Spindle Base",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 1,
    material: "Aluminium 6061-T6 (Tebal 10 mm)",
    specs: "113.12 × 106 × 10 mm, R10 Clamping Bore",
    function: "Dudukan penjepit motor spindle pendingin air/udara.",
    sheetRef: 18
  },
  {
    itemNo: 24,
    name: "Stepper Motor Bracket Z-Axis",
    partNumber: "Bracket motor z",
    category: "actuator",
    categoryLabel: "Aktuator & Motor",
    qty: 1,
    material: "Aluminium Plate 6061 (Tebal 8 mm)",
    specs: "58.22 × 56.4 × 8 mm",
    function: "Dudukan motor stepper NEMA 23 di bagian atas sumbu Z.",
    sheetRef: 17
  },
  {
    itemNo: 25,
    name: "Baut Countersunk M5 x 20",
    partNumber: "ISO 7046-2 - M5x20",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 15,
    material: "Steel Grade 8.8",
    specs: "M5 × 20 mm",
    function: "Pengikat pelat rangka dan dudukan rel.",
    sheetRef: 24
  },
  {
    itemNo: 26,
    name: "Baut Countersunk M4 x 20",
    partNumber: "ISO 7046-2 - M4x20",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 1,
    material: "Steel Grade 8.8",
    specs: "M4 × 20 mm",
    function: "Pengikat mikro dan bracket sensor.",
    sheetRef: 24
  },
  {
    itemNo: 27,
    name: "Baut Countersunk M5 x 14",
    partNumber: "ISO 7046-2 - M5x14",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 12,
    material: "Steel Grade 8.8",
    specs: "M5 × 14 mm",
    function: "Pengikat komponen bearing block SBR12UU.",
    sheetRef: 24
  },
  {
    itemNo: 28,
    name: "Baut Pan Head M6 x 40",
    partNumber: "ISO 7045 - M6x40",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 6,
    material: "Steel Grade 4.8",
    specs: "M6 × 40 mm",
    function: "Pengikat pelat gantry ke balok melintang 4080.",
    sheetRef: 24
  },
  {
    itemNo: 29,
    name: "Mur Tipis Segienam M5",
    partNumber: "ISO 4036 - M5",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 24,
    material: "Galvanized Steel",
    specs: "M5 Hex Nut (Thin)",
    function: "Pengunci baut rel linier dan pelat sambungan.",
    sheetRef: 24
  },
  {
    itemNo: 30,
    name: "Mur Tipis Segienam M6",
    partNumber: "ISO 4036 - M6",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 22,
    material: "Galvanized Steel",
    specs: "M6 Hex Nut (Thin)",
    function: "Pengunci baut pada alur slot aluminium ekstrusi T-Nut.",
    sheetRef: 24
  },
  {
    itemNo: 31,
    name: "Baut Pan Head M6 x 55",
    partNumber: "ISO 7045 - M6x55",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 2,
    material: "Steel Grade 4.8",
    specs: "M6 × 55 mm",
    function: "Pengikat melalui profil penopang kaki rangka.",
    sheetRef: 24
  },
  {
    itemNo: 32,
    name: "Baut Pan Head M6 x 35",
    partNumber: "ISO 7045 - M6x35",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 2,
    material: "Steel Grade 4.8",
    specs: "M6 × 35 mm",
    function: "Pengikat housing bearing.",
    sheetRef: 24
  },
  {
    itemNo: 33,
    name: "Baut Countersunk M5 x 35",
    partNumber: "ISO 7046-1 - M5x35",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 52,
    material: "Steel Grade 4.8",
    specs: "M5 × 35 mm",
    function: "Pengikat utama rel linier SBR12 ke alur ekstrusi aluminium.",
    sheetRef: 24
  },
  {
    itemNo: 34,
    name: "Baut Countersunk M10 x 40",
    partNumber: "ISO 7046-1 - M10x40",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 6,
    material: "Steel Grade 4.8",
    specs: "M10 × 40 mm",
    function: "Pengikat sudut rangka utama.",
    sheetRef: 24
  },
  {
    itemNo: 35,
    name: "Baut Countersunk M6 x 35",
    partNumber: "ISO 7046-1 - M6x35",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 8,
    material: "Steel Grade 4.8",
    specs: "M6 × 35 mm",
    function: "Pengikat pelat penyambung bawah.",
    sheetRef: 24
  },
  {
    itemNo: 36,
    name: "Baut Countersunk M6 x 40",
    partNumber: "ISO 7046-1 - M6x40",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 8,
    material: "Steel Grade 4.8",
    specs: "M6 × 40 mm",
    function: "Pengikat siku aluminium profil.",
    sheetRef: 24
  },
  {
    itemNo: 37,
    name: "Baut Socket Head Cap M5 x 50",
    partNumber: "BS EN ISO 4762 - M5x50",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 8,
    material: "Steel Grade 12.9 (High Strength)",
    specs: "M5 × 50 mm, Hex Socket Allen Key",
    function: "Pengikat modul bearing BK12/BF12 ke pelat muka.",
    sheetRef: 24
  },
  {
    itemNo: 38,
    name: "Baut Pan Head M5 x 14",
    partNumber: "ISO 7045 - M5x14",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 28,
    material: "Steel Grade 4.8",
    specs: "M5 × 14 mm",
    function: "Pengikat penutup kabel dan limit switch.",
    sheetRef: 24
  },
  {
    itemNo: 39,
    name: "Aluminium Corner Bracket 40x40 / 20x28",
    partNumber: "Corner Bracket 4040",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 8,
    material: "Die-Cast Aluminium Alloy",
    specs: "Dimensi 28 × 28 × 20 mm dengan 2x lubang baut M5/M6",
    function: "Menjaga siku rangka 90° tetap presisi dan bebas defleksi getaran.",
    sheetRef: 4
  },
  {
    itemNo: 40,
    name: "Baut Pan Head M6 x 14",
    partNumber: "ISO 7045 - M6x14",
    category: "fastener",
    categoryLabel: "Fastener & Baut",
    qty: 16,
    material: "Steel Grade 4.8",
    specs: "M6 × 14 mm",
    function: "Pengikat siku sudut ke profil aluminium.",
    sheetRef: 24
  },
  {
    itemNo: 41,
    name: "Bantalan Spacer Base Spindle",
    partNumber: "Bantalan base spindle",
    category: "structure",
    categoryLabel: "Rangka & Struktur",
    qty: 2,
    material: "Aluminium Alloy 6061",
    specs: "41 × 39 × 2.5 mm",
    function: "Pengatur presisi jarak dan alignment vertikal spindel terhadap meja.",
    sheetRef: 15
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { BOM_DATA };
}
